# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         constant-lexical
version:      2.0001
version_from: lib/constant/lexical.pm
installdirs:  site
requires:
    constant:                      1.03
    Sub::Delete:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
